### ISSUE TITLE
Invalid transaction when nonce=0

### ISSUE THREAD

**Issue by ckeenan** [ethereum/ethereumjs-lib#104]
Error when passing a signed transaction with nonce=0 to cpp-ethereum's `eth_injectTransaction`
```
┉┅▶  13:36:19|<unknown>  Ignoring invalid transaction: /private/var/folders/ll/3s6yt_ys52x7lzm1ld5_xjdm0000gn/T/cpp-ethereum20150504-88164-1fgjxzy/libethereum/../libdevcore/RLP.h(259): Throw in function _T dev::RLP::toInt(int) const [_T = boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<256, 256, 0, 0, void>, 0>]
Dynamic exception type: boost::exception_detail::clone_impl<dev::BadCast>
std::exception::what: std::exception
[dev::eth::tag_field*] = 0
[dev::eth::tag_data*] = 00
[dev::eth::tag_field*] = invalid transaction format
```
Setting the nonce="" works

**Comment by wanderer** [comment]
thanks @ckeenan, I probably need to change what `nonce` defaults to then. Are you on the Dev branch?

**Comment by ckeenan** [comment]
Cool, thanks! I was on master. Just tried this on develop and got the same thing. The default value might actually be working too -- when nonce is not set it also works fine

**Comment by wanderer** [comment]
Note to self: 0 should go to `new Buffer([])`

**Comment by wanderer** [comment]
@ckeenan This is fixed. Also moved Tx's into thier own module. https://github.com/ethereum/ethereumjs-tx
