### ISSUE TITLE
runBlock() fails with the error undefinedinvalid receiptTrie

### ISSUE THREAD

**Issue by asinyagin** [ethereum/ethereumjs-lib#116]
Hey,

I don't know how to run a block in VM. I run that code (the full example is here https://github.com/asinyagin/ethereumjs-test/blob/master/app.js):
```javascript
...
function sendTx(cb) {
  var tx = new Ethereum.Transaction();
  tx.to = new Buffer('cd2a3d9f938e13cd947ec05abc7fe734df8dd825', 'hex');
  tx.value = 1000000;
  tx.sign(new Buffer(sha3(accountKey), 'hex'));
  var block = new Ethereum.Block({
    header: {
      coinbase: new Buffer(accountAddress, 'hex'),
      gasLimit: 1000000000,
      number: 0,
      timestamp: new Buffer(pad(Date.now().toString(16)), 'hex')
    },
    transactions: [ tx.serialize() ],
    uncleHeaders: []
  });
  vm.runBlock({ block: block, blockchain: blockchain }, cb);
}
...
```
But `runBlock()` fails with the error `undefinedinvalid receiptTrie` in the code at runBlock.js:
```javascript
      self.trie.commit(function(err) {
        self.cache.flush(function() {
          if (!opts.gen) {
            if (receiptTrie.root && receiptTrie.root.toString('hex') !== opts.block.header.receiptTrie.toString('hex'))
              err += 'invalid receiptTrie '
            else if (bloom.bitvector.toString('hex') !== opts.block.header.bloom.toString('hex'))
              err += 'invalid bloom '
```

Do I use `runBlock()` in a wrong way?

**Comment by wanderer** [comment]
You need add `generate: true` to `runBlock()`.  The reason is that normal when a block comes in from the network it includes the stateRoot that the trie should have when the block is done running. Since you didn't set the stateRoot when you created the block it got defaulted to `0x00`. the `generate` param generates stateRoot for the block. This is usefully when you are creating blocks.

**Comment by wanderer** [comment]
aslo @asinyagin here is the modified example. https://gist.github.com/wanderer/de5badbb055a62b71fcc Notice, I'm not using ethereumjs-lib, instead I'm using the submodules directly. They are more cutting edge and new api and will be pulled into ethereumjs-lib when they are ready.
