### ISSUE TITLE
Export account to keystore json?

### ISSUE THREAD

**Issue by tinybike** [ethereum/ethereumjs-lib#117]
Does ethereumjs-lib presently have a method to create a [properly-formatted "secret storage" json](https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition) (the format that geth reads from the `~/.ethereum/keystore` directory)?

Asking because I'm writing this for [augur.js](https://github.com/AugurProject/augur.js) but would like to avoid reinventing the wheel if it's already buried somewhere in this lib!

**Comment by wanderer** [comment]
nope! but that would be a nice module to have :+1:

**Comment by tinybike** [comment]
https://github.com/AugurProject/ethereumjs-keys :)

**Comment by tinybike** [comment]
Btw, let me know if you'd prefer I didn't use the ethereumjs-* namespace -- I'm realizing most (all?) of the other ethereumjs repos are offshoots of ethereumjs-lib.  Don't mean to step on any toes with this!

**Comment by tinybike** [comment]
...never mind, I renamed it [keythereum](https://github.com/AugurProject/keythereum) because comedy :D

**Comment by wanderer** [comment]
@tinybike  nice and im totally cool with you using ethereumjs-* It makes search for modules easyier :)
