### ISSUE TITLE
about transactions and blocks 

### ISSUE THREAD

**Issue by romanman** [ethereum/ethereumjs-lib#118]
Hey @wanderer , we are running transaction 
once as in block and the other case as the 
simple tx, looks like as inside the block 
we need some good way to get the return value, 
any idea ?

@asinyagin

**Comment by wanderer** [comment]
Maybe I could add in extra output to the traceStream.

**Comment by wanderer** [comment]
@romanman; @asinyagin I just added `vm.afterTx` hook that get run after each tx. Use like this

```
vm = new VM()
vm.afterTx = function(txResults, continue){
    //do some stuff with `txResults`
    ...
    //unpause the vm
    continue()
}
```

**Comment by wanderer** [comment]
also im going to move this issue to `ethereumjs-vm`

**Comment by romanman** [comment]
@alex

**Comment by romanman** [comment]
@asinyagin
