### ISSUE TITLE
installation error - secp256k1@1.1.1?

### ISSUE THREAD

**Issue by mtgran** [ethereum/ethereumjs-lib#119]
Hi,

during the installation of ethereumjs-lib (npm install ethereumjs-lib), I get the following error (secp256k1@1.1.1 problem?):

------------------------------------------------------------------------------------

../functions.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Sign(Nan::NAN_METHOD_ARGS_TYPE)’:
../functions.cc:66:59: error: no matching function for call to ‘v8::Array::Set(int, node::Buffer*)’
       results->Set(0, node::Buffer::New(output, outputlen));
                                                           ^
../functions.cc:66:59: note: candidates are:
In file included from /usr/include/nodejs/src/node.h:62:0,
                 from ../node_modules/nan/nan.h:24,
                 from ../functions.cc:1:
/usr/include/nodejs/deps/v8/include/v8.h:1483:17: note: bool v8::Object::Set(v8::Handle<v8::Value>, v8::Handle<v8::Value>, v8::PropertyAttribute)
   V8EXPORT bool Set(Handle<Value> key,
                 ^
/usr/include/nodejs/deps/v8/include/v8.h:1483:17: note:   no known conversion for argument 1 from ‘int’ to ‘v8::Handle<v8::Value>’
/usr/include/nodejs/deps/v8/include/v8.h:1487:17: note: bool v8::Object::Set(uint32_t, v8::Handle<v8::Value>)
   V8EXPORT bool Set(uint32_t index,
                 ^
/usr/include/nodejs/deps/v8/include/v8.h:1487:17: note:   no known conversion for argument 2 from ‘node::Buffer*’ to ‘v8::Handle<v8::Value>’
/usr/include/nodejs/deps/v8/include/v8.h: In instantiation of ‘v8::Local<T>::Local(S*) [with S = node::Buffer; T = v8::Value]’:
.././async.h:42:5:   required from here
/usr/include/nodejs/deps/v8/include/v8.h:281:60: error: no matching function for call to ‘v8::Handle<v8::Value>::Handle(node::Buffer*&)’
   template <class S> inline Local(S* that) : Handle<T>(that) { }
                                                            ^
/usr/include/nodejs/deps/v8/include/v8.h:281:60: note: candidates are:
/usr/include/nodejs/deps/v8/include/v8.h:196:29: note: template<class S> v8::Handle<T>::Handle(v8::Handle<S>)
   template <class S> inline Handle(Handle<S> that)
                             ^
/usr/include/nodejs/deps/v8/include/v8.h:196:29: note:   template argument deduction/substitution failed:
/usr/include/nodejs/deps/v8/include/v8.h:281:60: note:   mismatched types ‘v8::Handle<T>’ and ‘node::Buffer*’
   template <class S> inline Local(S* that) : Handle<T>(that) { }
                                                            ^
/usr/include/nodejs/deps/v8/include/v8.h:184:19: note: v8::Handle<T>::Handle(T*) [with T = v8::Value]
   inline explicit Handle(T* val) : val_(val) {}
                   ^
/usr/include/nodejs/deps/v8/include/v8.h:184:19: note:   no known conversion for argument 1 from ‘node::Buffer*’ to ‘v8::Value*’
/usr/include/nodejs/deps/v8/include/v8.h:179:10: note: v8::Handle<T>::Handle() [with T = v8::Value]
   inline Handle() : val_(0) {}
          ^
/usr/include/nodejs/deps/v8/include/v8.h:179:10: note:   candidate expects 0 arguments, 1 provided
/usr/include/nodejs/deps/v8/include/v8.h:174:26: note: v8::Handle<v8::Value>::Handle(const v8::Handle<v8::Value>&)
 template <class T> class Handle {
                          ^
/usr/include/nodejs/deps/v8/include/v8.h:174:26: note:   no known conversion for argument 1 from ‘node::Buffer*’ to ‘const v8::Handle<v8::Value>&’
In file included from ../functions.cc:1:0:
../node_modules/nan/nan_callbacks_pre_12_inl.h: In instantiation of ‘void Nan::ReturnValue<T>::Set(S*) [with S = node::Buffer; T = v8::Value]’:
../functions.cc:106:77:   required from here
../node_modules/nan/nan.h:124:40: error: cannot convert ‘v8::Primitive*’ to ‘node::Buffer** volatile’ in assignment
       *(static_cast<T *volatile *>(0)) = static_cast<S*>(0);                   \
                                        ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:97:34: note: in expansion of macro ‘TYPE_CHECK’
   inline void Set(S *whatever) { TYPE_CHECK(S*, v8::Primitive); }
                                  ^
make: *** [Release/obj.target/secp256k1/functions.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.19.0-26-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/m9000/node_modules/ethereumjs-lib/node_modules/ethereumjs-tx/node_modules/secp256k1
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 

gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: ENOENT, no such file or directory
gyp ERR! stack     at process.cwd (/usr/lib/nodejs/graceful-fs/polyfills.js:8:19)
gyp ERR! stack     at Object.exports.resolve (path.js:309:52)
gyp ERR! stack     at configure (/usr/share/node-gyp/lib/configure.js:26:23)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as configure] (/usr/share/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at run (/usr/share/node-gyp/bin/node-gyp.js:72:30)
gyp ERR! stack     at process._tickCallback (node.js:415:13)
gyp ERR! System Linux 3.19.0-26-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"

/usr/lib/nodejs/graceful-fs/polyfills.js:8
    cwd = origCwd.call(process)
                  ^
Error: ENOENT, no such file or directory
    at process.cwd (/usr/lib/nodejs/graceful-fs/polyfills.js:8:19)
    at errorMessage (/usr/share/node-gyp/bin/node-gyp.js:119:28)
    at issueMessage (/usr/share/node-gyp/bin/node-gyp.js:125:3)
    at process.<anonymous> (/usr/share/node-gyp/bin/node-gyp.js:109:3)
    at process.EventEmitter.emit (events.js:95:17)
    at process._fatalException (node.js:272:26)
npm ERR! secp256k1@1.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@1.1.1 install script.
npm ERR! This is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.19.0-26-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "ethereumjs-lib"
npm ERR! cwd /home/m9000
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
chdir(): No such file or directory

**Comment by mtgran** [comment]
Hello, sorry, here all the log:

---------------------------------------------------------------


m9000@Merlin:~$ sudo npm install ethereumjs-lib
[sudo] password for m9000: 
 
> secp256k1@0.0.16 install /home/m9000/node_modules/ethereumjs-lib/node_modules/secp256k1
> node-gyp rebuild

make: Entering directory '/home/m9000/node_modules/ethereumjs-lib/node_modules/secp256k1/build'
  CXX(target) Release/obj.target/secp256k1/secp256k1.o
  CC(target) Release/obj.target/secp256k1/secp256k1-src/src/secp256k1.o
  SOLINK_MODULE(target) Release/obj.target/secp256k1.node
  SOLINK_MODULE(target) Release/obj.target/secp256k1.node: Finished
  COPY Release/secp256k1.node
make: Leaving directory '/home/m9000/node_modules/ethereumjs-lib/node_modules/secp256k1/build'

> secp256k1@1.1.1 install /home/m9000/node_modules/ethereumjs-lib/node_modules/ethereumjs-tx/node_modules/secp256k1
> node-gyp rebuild

make: Entering directory '/home/m9000/node_modules/ethereumjs-lib/node_modules/ethereumjs-tx/node_modules/secp256k1/build'
  CXX(target) Release/obj.target/secp256k1/functions.o
../functions.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Sign(Nan::NAN_METHOD_ARGS_TYPE)’:
../functions.cc:66:59: error: no matching function for call to ‘v8::Array::Set(int, node::Buffer*)’
       results->Set(0, node::Buffer::New(output, outputlen));
                                                           ^
../functions.cc:66:59: note: candidates are:
In file included from /usr/include/nodejs/src/node.h:62:0,
                 from ../node_modules/nan/nan.h:24,
                 from ../functions.cc:1:
/usr/include/nodejs/deps/v8/include/v8.h:1483:17: note: bool v8::Object::Set(v8::Handle<v8::Value>, v8::Handle<v8::Value>, v8::PropertyAttribute)
   V8EXPORT bool Set(Handle<Value> key,
                 ^
/usr/include/nodejs/deps/v8/include/v8.h:1483:17: note:   no known conversion for argument 1 from ‘int’ to ‘v8::Handle<v8::Value>’
/usr/include/nodejs/deps/v8/include/v8.h:1487:17: note: bool v8::Object::Set(uint32_t, v8::Handle<v8::Value>)
   V8EXPORT bool Set(uint32_t index,
                 ^
/usr/include/nodejs/deps/v8/include/v8.h:1487:17: note:   no known conversion for argument 2 from ‘node::Buffer*’ to ‘v8::Handle<v8::Value>’
/usr/include/nodejs/deps/v8/include/v8.h: In instantiation of ‘v8::Local<T>::Local(S*) [with S = node::Buffer; T = v8::Value]’:
.././async.h:42:5:   required from here
/usr/include/nodejs/deps/v8/include/v8.h:281:60: error: no matching function for call to ‘v8::Handle<v8::Value>::Handle(node::Buffer*&)’
   template <class S> inline Local(S* that) : Handle<T>(that) { }
                                                            ^
/usr/include/nodejs/deps/v8/include/v8.h:281:60: note: candidates are:
/usr/include/nodejs/deps/v8/include/v8.h:196:29: note: template<class S> v8::Handle<T>::Handle(v8::Handle<S>)
   template <class S> inline Handle(Handle<S> that)
                             ^
/usr/include/nodejs/deps/v8/include/v8.h:196:29: note:   template argument deduction/substitution failed:
/usr/include/nodejs/deps/v8/include/v8.h:281:60: note:   mismatched types ‘v8::Handle<T>’ and ‘node::Buffer*’
   template <class S> inline Local(S* that) : Handle<T>(that) { }
                                                            ^
/usr/include/nodejs/deps/v8/include/v8.h:184:19: note: v8::Handle<T>::Handle(T*) [with T = v8::Value]
   inline explicit Handle(T* val) : val_(val) {}
                   ^
/usr/include/nodejs/deps/v8/include/v8.h:184:19: note:   no known conversion for argument 1 from ‘node::Buffer*’ to ‘v8::Value*’
/usr/include/nodejs/deps/v8/include/v8.h:179:10: note: v8::Handle<T>::Handle() [with T = v8::Value]
   inline Handle() : val_(0) {}
          ^
/usr/include/nodejs/deps/v8/include/v8.h:179:10: note:   candidate expects 0 arguments, 1 provided
/usr/include/nodejs/deps/v8/include/v8.h:174:26: note: v8::Handle<v8::Value>::Handle(const v8::Handle<v8::Value>&)
 template <class T> class Handle {
                          ^
/usr/include/nodejs/deps/v8/include/v8.h:174:26: note:   no known conversion for argument 1 from ‘node::Buffer*’ to ‘const v8::Handle<v8::Value>&’
In file included from ../functions.cc:1:0:
../node_modules/nan/nan_callbacks_pre_12_inl.h: In instantiation of ‘void Nan::ReturnValue<T>::Set(S*) [with S = node::Buffer; T = v8::Value]’:
../functions.cc:106:77:   required from here
../node_modules/nan/nan.h:124:40: error: cannot convert ‘v8::Primitive*’ to ‘node::Buffer** volatile’ in assignment
       *(static_cast<T *volatile *>(0)) = static_cast<S*>(0);                   \
                                        ^
../node_modules/nan/nan_callbacks_pre_12_inl.h:97:34: note: in expansion of macro ‘TYPE_CHECK’
   inline void Set(S *whatever) { TYPE_CHECK(S*, v8::Primitive); }
                                  ^
secp256k1.target.mk:119: recipe for target 'Release/obj.target/secp256k1/functions.o' failed
make: *** [Release/obj.target/secp256k1/functions.o] Error 1
make: Leaving directory '/home/m9000/node_modules/ethereumjs-lib/node_modules/ethereumjs-tx/node_modules/secp256k1/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.19.0-26-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/m9000/node_modules/ethereumjs-lib/node_modules/ethereumjs-tx/node_modules/secp256k1
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 

> sha3@1.1.0 install /home/m9000/node_modules/ethereumjs-lib/node_modules/sha3
> node-gyp rebuild


gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: ENOENT, no such file or directory
gyp ERR! stack     at process.cwd (/usr/lib/nodejs/graceful-fs/polyfills.js:8:19)
gyp ERR! stack     at Object.exports.resolve (path.js:309:52)
gyp ERR! stack     at configure (/usr/share/node-gyp/lib/configure.js:26:23)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as configure] (/usr/share/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at run (/usr/share/node-gyp/bin/node-gyp.js:72:30)
gyp ERR! stack     at process._tickCallback (node.js:415:13)
gyp ERR! System Linux 3.19.0-26-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"

/usr/lib/nodejs/graceful-fs/polyfills.js:8
    cwd = origCwd.call(process)
                  ^
Error: ENOENT, no such file or directory
    at process.cwd (/usr/lib/nodejs/graceful-fs/polyfills.js:8:19)
    at errorMessage (/usr/share/node-gyp/bin/node-gyp.js:119:28)
    at issueMessage (/usr/share/node-gyp/bin/node-gyp.js:125:3)
    at process.<anonymous> (/usr/share/node-gyp/bin/node-gyp.js:109:3)
    at process.EventEmitter.emit (events.js:95:17)
    at process._fatalException (node.js:272:26)
npm ERR! secp256k1@1.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@1.1.1 install script.
npm ERR! This is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.19.0-26-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "ethereumjs-lib"
npm ERR! cwd /home/m9000
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/m9000/npm-debug.log
npm ERR! not ok code 0

**Comment by wanderer** [comment]
hi @mtgran what node version are you using?

**Comment by mtgran** [comment]
$ node -v
v0.10.25

**Comment by wanderer** [comment]
can you try node version 0.11 or greater?
https://github.com/wanderer/secp256k1-node won't work on 10.

**Comment by mtgran** [comment]
it works, thanks a lot!
