### ISSUE TITLE
Missing "r"s in the readme

### ISSUE THREAD

**Issue by toomim** [ethereum/ethereumjs-lib#122]
The readme mentions a "vitual" machine, and a "Recusive" length prefix serialization.

Did somebody write this on a keyboard with a broken "r" key? ;) It's actually kind of cute. :)

**Comment by wanderer** [comment]
um yeah that would be me. I also do that with 's' sometime. I think my brain just blanks them out... idk because I really can't tell when they are missing.

**Comment by toomim** [comment]
lol

**Comment by ethers** [comment]
@toomim feel free to submit a PR, you'll be a contributor and all helpful contributions are welcome :)

**Comment by toomim** [comment]
I can be a contributor??? Ok, you convinced me!

**Comment by kumavis** [comment]
:rocket: to the moon

**Comment by toomim** [comment]
Uh, your baby is too cute.
