### ISSUE TITLE
Module did not self-register

### ISSUE THREAD

**Issue by forgetso** [ethereum/ethereumjs-lib#77]
Hi, running node index.js after installing the package gives me this error:

node index.js
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/chris/ethereumjs-lib/lib/utils.js:1:76)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

node --version
v0.13.0-pre

npm --version
1.3.10

Additionally, node-debug index.js gives the following:

Debugging `index.js`

/usr/local/bin/node: symbol lookup error: /usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.3.3/node-v14-linux-x64/debug.node: undefined symbol: _ZN2v86Script7CompileENS_6HandleINS_6StringEEEPNS_12ScriptOriginEPNS_10ScriptDataE

Any tips on how I can get this running?

**Comment by wanderer** [comment]
weird i have never seen this error.  Can you post what is in your index.js? Also did you install from npm or git?

**Comment by forgetso** [comment]
Hi wanderer, I managed to solve the issue. Initially, installed npm with sudo apt-get npm whilst not having nodejs installed. This pulls down node v0.13.something-pre with it and causes problems with node-gyp.

Similar Issue:
https://github.com/Automattic/node-canvas/issues/433

The solution was to remove npm and node, download the node sources, make and install. I then installed npm from sudo apt-get npm. My versions are now:

chris@chris-HP-G61-Notebook-PC:~/ethereumjs-lib$ node --version
v0.10.35
chris@chris-HP-G61-Notebook-PC:~/ethereumjs-lib$ npm --version
1.3.10

Anyway, I now have a VM running for the first time! I have literally been trying to do this for weeks.

**Comment by wanderer** [comment]
awesome! let me know if you run into another issues.

**Comment by forgetso** [comment]
wanderer, are you in the ethereum-dev skype chat?

**Comment by wanderer** [comment]
yes im, null_radix on skype and IRC
