### ISSUE TITLE
get address from string ? 

### ISSUE THREAD

**Issue by romanman** [ethereum/ethereumjs-lib#79]
Is it available already 
to make address out of 
string:  like `pubKey("cat")  = 79b08ad8787060333663d19704909ee7b1903e58` ?

**Comment by wanderer** [comment]
you can do something like this.
```javascript
var ethUtils = require('ethereumjs-lib').utils;

var hash = ethUtils.sha3('cat');
var address = ethUtils.pubToAddress(hash)

**Comment by romanman** [comment]
nice,  I guess it should be `privToAddress`

**Comment by wanderer** [comment]
that would make more sense. But I don't have that function. I Will add it.

**Comment by romanman** [comment]
I mean `ethUtils.sha3('cat');` is the private key 
that you sign the transaction , so the name 
should change , what do you think ?

**Comment by wanderer** [comment]
Ok so maybe this is what you want.

```javascript 
var ecdsa = require('secp256k1');
var ethUtils = require('ethereumjs-lib').utils;

var privateKey = ethUtils.sha3('cat');
var publicKey = ecdsa.createPublicKey(privateKey);
var address = ethUtils.pubToAddress(publicKey)
```

**Comment by romanman** [comment]
ohh yeah , thanks.

**Comment by wanderer** [comment]
give it try and let me know it works for you!

**Comment by romanman** [comment]
we already got the sign transaction to work 
in the browser , it opens really cool options :)

**Comment by wanderer** [comment]
awesome! I haven't actully tried signing tx's in the browser recently. So
let me know if you run any problems

**Comment by romanman** [comment]
(y)
