### ISSUE TITLE
Nonce property definition is inconsistent with other TX properties

### ISSUE THREAD

**Issue by projected1** [ethereum/ethereumjs-lib#83]
In the example bellow, all properties except for "nonce", are well defined. They are either big numbers or strings that are implicitly converted into buffers by the lib. Nonce, however, has to be explicitly converted into a Buffer by the caller. If nonce is "0" ("00"), the lib also accepts a null object ({nonce:null}) which is inconsistent with the other properties (can't use null for value for example).

```
var txRaw = {
    nonce: bignum(0).toBuffer(), // or "null"
    gasPrice: bignum(1000000000000),
    gasLimit: bignum(10000),
    to: '13978aee95f38490e9769c39b2773ed763d9cd5f',
    value: bignum(10000000000000000),
    data: ''
};
var tx = new Transaction(txRaw);
```

**Comment by wanderer** [comment]
yes this is an ugly thing. We need to make it more consistent. So here is what I propose any field can be a `bignum`, `buffer` or `hex string` .  Now some fields can be `null` for example data and some can't be for example `gasLimit` so we need that ability to set some fields to null still.

**Comment by wanderer** [comment]
ok this is fixed on develop. I rewrote how the schema definitions are handled. `blocks`, `blockheaders`, `transactions` and `accounts` can have their properties be either and buffer, number, bignum, or hex string. Underneath everything is a still a buffer.
