### ISSUE TITLE
simulation testing integration

### ISSUE THREAD

**Issue by ethers** [ethereum/ethereumjs-lib#85]
should integrate with Christoph's simulated tests #67

**Comment by wanderer** [comment]
@CJentzsch do you know how i can get started on this?

**Comment by CJentzsch** [comment]
I need working install instructions for Ubuntu 14.04 and an executable which takes a string as commandline argument (which is the contents of the vm test json file) and returns 0/1 for passed/failed. I will include that in my bash script.

**Comment by wanderer** [comment]
currently the test runner loads that actually tests too. Can we do some thing like this `stateTests --file <filename>  --test <testname> ` ? or would that mess up your system?

**Comment by wanderer** [comment]
how does are test runner know what kinda of test its running? for example vmTests get setup differently than stateTests

**Comment by CJentzsch** [comment]
The random test simulation os only for VM tests

**Comment by CJentzsch** [comment]
Here is an example of what I need. This is for the go client, they provided me with the executable ethtest:
ethtest '{
>     "randomVMtest" : {
>         "env" : {
>             "currentCoinbase" : "2adc25665018aa1fe0e6bc666dac8fc2697ff9ba",
>             "currentDifficulty" : "256",
>             "currentGasLimit" : "1000000",
>             "currentNumber" : "0",
>             "currentTimestamp" : "1",
>             "previousHash" : "5e20a0453cecd065ea59c37ac63e079ee08998b6045136a8ce6635c7912ec0b6"
>         },
>         "exec" : {
>             "address" : "0f572e5295c57f15886f9b263e2f6d2d6c7b5ec6",
>             "caller" : "cd1722f3947def4cf144679da39c4c32bdc35681",
>             "code" : "0x0c0b8a4494328e02",
>             "data" : "0x",
>             "gas" : "10000",
>             "gasPrice" : "100000000000000",
>             "origin" : "cd1722f3947def4cf144679da39c4c32bdc35681",
>             "value" : "1000000000000000000"
>         },
>         "pre" : {
>             "0f572e5295c57f15886f9b263e2f6d2d6c7b5ec6" : {
>                 "balance" : "1000000000000000000",
>                 "code" : "0x0c0b8a4494328e02",
>                 "nonce" : "0",
>                 "storage" : {
>                 }
>             }
>         }
>     }
> }'

This returns 0 if successfull, and 1 if it failed.

**Comment by wanderer** [comment]
how do we check success here? There is no post condition to check against.

**Comment by CJentzsch** [comment]
No post conditions means that the test throw an OOG exception (the same is true for the current VM tests, there is no difference)

**Comment by wanderer** [comment]
gotcha thanks @CJentzsch !

**Comment by CJentzsch** [comment]
no problem.

**Comment by wanderer** [comment]
@CJentzsch  ok i wrote a test runner accouding  to the above specs execpt that it run state tests instead of VM test. Is it still the plan to switch to state tests? its is here https://github.com/ethereum/ethereumjs-tester I need to test it on ubuntu and write install instructions yet.

**Comment by wanderer** [comment]
ok instructions here https://github.com/ethereum/ethereumjs-lib/wiki/Installation-Linux

**Comment by wanderer** [comment]
hey @CJentzsch just checking in. I have a test runner now. Are we running state tests yet?

**Comment by CJentzsch** [comment]
Not yet (waiting for go and python to deliver a state test runner), but I will check your test runner and start using it locally. I will let you know about the progress.

**Comment by wanderer** [comment]
ok we are passing all the PoC9 state tests

**Comment by CJentzsch** [comment]
Today was the first day the cpp, cpp-jit, python and go did run the test simulation on big scale. Now I will try to add JS and Java.
