### ISSUE TITLE
blockchain get blocks by number

### ISSUE THREAD

**Issue by wanderer** [ethereum/ethereumjs-lib#89]
need to get blocks by numbers.

**Comment by kumavis** [comment]
we can do this now, right?

**Comment by wanderer** [comment]
so yes you can but its undocumented and messy. So noone is suppose to know that you can do it,

**Comment by kumavis** [comment]
haha ok

**Comment by asinyagin** [comment]
@wanderer @kumavis guys, can you tell more about that rpc? is that json rpc interface for ethereumjs? if it is, is it supposed to be public? i'm working on json rpc for our ethereum sandbox based on ethereumjs, so if there will be some built-in solution, i would be glad to test and use it in our product =)

**Comment by asinyagin** [comment]
sorry, didn't notice the date =)

**Comment by wanderer** [comment]
@asinyagin its being rewitten here https://github.com/ethereum/ethereumjs-blockchain

**Comment by wanderer** [comment]
@asinyagin @kumavis this is done
