### ISSUE TITLE
Browserify fails due to Node package dependencies

### ISSUE THREAD

**Issue by projected1** [ethereum/ethereumjs-lib#97]
Fails with the following error:
```TypeError: process.versions is undefined```

The binding package depends on the process package.
Three packages depend on the binding package:
1. sha3
2. nan
3. secp256k1

SHA3 dependency issues are solved via browser/sha3.js.
The other two libs causes browserify to fail.

This behavior is confirmed browserifying secp256k1 as a standalone lib.

**Comment by wanderer** [comment]
yep those are suppose to be replaced by shims here https://github.com/ethereum/ethereumjs-lib/blob/develop/package.json#L70-L71 Can you conform which branch you are on?

**Comment by wanderer** [comment]
@projected1 any luck here? I still can not replicate

**Comment by kumavis** [comment]
closing this for now -- @projected1 let us know if you're still running into this.
